- name: release
  color: "11a612"
  description: Triggers the release pipeline on merge to main

- name: chore
  color: "e4e669"
  description: Maintenance, refactoring, tooling

- name: dependencies
  color: "179d99"
  description: Dependency updates

- name: documentation
  color: "0075ca"
  description: "Improvements or additions to documentation"
